---
- name: Add APT repository
  apt_repository:
    repo: "ppa:rael-gc/rvm"
    state: present

# Установим в цикле все зависимости
- name: Update and upgrade apt packages
  apt:
  # upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  # state: fixed

- name: Install ruby and rubygems and required packages
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    # - ruby-bundler
    - build-essential
    - git
    - policykit-1
    - rvm
  tags: ruby
  
- name: Install bundler 1.16.1
  gem:
    name: bundler
    version: 1.16.1
    state: present
  become: true

