- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
      # upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      # state: fixed

    - name: Install git
      apt:
        name: git
        state: present

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      notify:
        - restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"

  handlers:
  - name: restart puma
    service: name=puma state=restarted
